Fixes compilation for CUDA 8.0.
If `using namespace std` was present, caused errors:
```
/usr/local/cuda-8.0/include/cuda_fp16.h(3068): error: more than one instance of overloaded function "isinf" matches the argument list:
function "isinf(float)"
function "std::isinf(float)"
argument types are: (float)
```