Fixed the issue with NVCC 7.5 and GCC 5
Ends up in error error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
Needs to be tested on older GCC.